services:
  - type: web
    name: yolov8-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MODEL_PATH
        value: my_model1.pt  # Atur sesuai nama modelmu
